#!/usr/bin/env python3
"""Emit the LaTeX for section 3: cluster table, injection figure, example boxes, appendix.

Generated rather than hand-typed for two reasons. The numbers stay tied to the result files,
so they cannot drift from what was measured. And the character-noise spans are full of
LaTeX specials -- backslashes, dollars, hashes, carets, tildes, braces -- which are easy to
mis-escape by hand and which silently break a build or, worse, render as something else.

Run: python make_paper_snippets.py --out paper_section3.tex
"""
import argparse, difflib, json, os
from collections import defaultdict

CLUSTERS = ["chars", "negation", "touchy", "harmful_phrase", "action"]
LABEL = {"chars": "Characters", "negation": "Negation", "touchy": "Touchy subject",
         "harmful_phrase": "Harmful-sounding phrase", "action": "Action words"}
DESC = {"chars": "asterisks, slashes, punctuation runs, stray symbols",
        "negation": "an appended \\emph{no}, \\emph{not}, \\emph{NOT PLEASE}",
        "touchy": "the model's own nature, social topics, privacy",
        "harmful_phrase": "alarming wording that is not actually harmful",
        "action": "task or imperative verbs inserted"}
ARM_ORDER = ["chars", "action", "negation", "harmful_phrase", "touchy",
             "chars+negation", "chars+touchy", "chars+harmful_phrase", "all_five"]
ARM_LABEL = {"chars": "Characters", "action": "Action words", "negation": "Negation",
             "harmful_phrase": "Harmful-sounding phrase", "touchy": "Touchy subject",
             "chars+negation": "Characters + negation", "chars+touchy": "Characters + touchy",
             "chars+harmful_phrase": "Characters + harmful phrase",
             "all_five": "All five combined"}

SPECIAL = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
           "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
           "^": r"\textasciicircum{}"}

# A box is a claim in the paper, so it has to survive being read by a referee. The response
# judge is ~94% precise on this data -- it labelled "A clever challenge! ... the palindrome
# is: 'level'" as a refusal -- and one such case did reach a rendered box. Boxes therefore
# additionally require the response to actually contain a refusal phrase. Any category with
# no example clearing that bar simply gets no box, which is the honest outcome: the two
# categories that fail this are the two the causal test finds inert anyway.
REFUSAL_PHRASE = [
    "i cannot", "i can't", "i can not", "i'm sorry", "i am sorry", "i apologize",
    "i'm not able", "i am not able", "i'm unable", "i am unable", "i must decline",
    "cannot fulfill", "cannot provide", "cannot assist", "can't help", "can't provide",
    "can't assist", "cannot create", "cannot generate", "can't create", "can't generate",
    "cannot write", "cannot help", "i won't", "i will not", "unable to",
]


def is_refusal(t):
    return any(p in (t or "").lower()[:300] for p in REFUSAL_PHRASE)


def esc(s):
    return "".join(SPECIAL.get(c, c) for c in (s or ""))


def trim(s, n):
    s = " ".join((s or "").split())
    return s if len(s) <= n else s[:n - 1].rstrip() + "\u2026"


def marked(base, inj, n=300):
    """Escaped rewrite with inserted regions wrapped in \\hl{}."""
    inj = trim(inj, n)
    sm = difflib.SequenceMatcher(None, base, inj, autojunk=False)
    out = []
    for tag, _, _, j1, j2 in sm.get_opcodes():
        seg = inj[j1:j2]
        if not seg:
            continue
        out.append(f"\\ins{{{esc(seg)}}}" if tag in ("insert", "replace") else esc(seg))
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--clusters", default="probe_or/results/gcg_clusters_llama.json")
    ap.add_argument("--judged", default="probe_or/results/injections_llama_judged.json")
    ap.add_argument("--benign", default="probe_or/results/injections_llama_benign.json")
    ap.add_argument("--out", default="paper_section3.tex")
    a = ap.parse_args()

    rows = json.load(open(a.clusters))
    n = len(rows)
    share = {k: sum(1 for r in rows if k in r["clusters"]) for k in CLUSTERS}
    none = sum(1 for r in rows if not r["clusters"])
    multi = sum(1 for r in rows if len(r["clusters"]) >= 2)

    clean = {t: json.load(open(f"probe_or/results/injections_{t}_clean_summary.json"))
             for t in ("llama", "qwen")}

    jd = json.load(open(a.judged))["rows"]
    by = defaultdict(dict)
    for r in jd:
        by[r["arm"]][r["idx"]] = r
    base = by["baseline"]
    ben = {(r["arm"], r["idx"]): r.get("benign", "")
           for r in json.load(open(a.benign))["rows"]} if os.path.exists(a.benign) else {}

    L = []
    w = L.append
    w("% ============================================================================")
    w("% Generated by make_gcg_paper_snippets.py -- do not hand-edit; regenerate.")
    w("% Preamble additions required:")
    w("%   \\usepackage[most]{tcolorbox}")
    w("%   \\newcommand{\\ins}[1]{\\textcolor{insred}{\\bfseries #1}}")
    w("%   \\definecolor{insred}{HTML}{C0392B}")
    w("%   \\definecolor{boxgrey}{HTML}{F7F7F5}")
    w("% ============================================================================")
    w("")

    # ---- Table: cluster shares -------------------------------------------------
    w("\\begin{table}[t]")
    w("\\centering")
    w("\\small")
    w(f"\\caption{{\\textbf{{What the gradient search inserts.}} Claude Sonnet~5 sorted all "
      f"{n:,} accepted Llama rewrites into five categories derived from a manual reading of "
      f"a labelled sample. Categories are not exclusive: {100*multi/n:.0f}\\% of rewrites "
      f"carry two or more, and only {100*none/n:.1f}\\% carry none, so the five together "
      f"describe {100*(n-none)/n:.1f}\\% of the corpus.}}")
    w("\\label{tab:gcg-clusters}")
    w("\\begin{tabular}{llrr}")
    w("\\toprule")
    w("Category & What it covers & Rewrites & Share \\\\")
    w("\\midrule")
    for k in sorted(CLUSTERS, key=lambda x: -share[x]):
        w(f"{LABEL[k]} & {DESC[k]} & {share[k]:,} & {100*share[k]/n:.1f}\\% \\\\")
    w("\\midrule")
    w(f"None of the five & & {none} & {100*none/n:.1f}\\% \\\\")
    w("\\bottomrule")
    w("\\end{tabular}")
    w("\\end{table}")
    w("")

    # ---- Figure ----------------------------------------------------------------
    w("\\begin{figure}[t]")
    w("  \\centering")
    w("  \\includegraphics[width=\\linewidth]{figures/fig_injection_effect}")
    lla, qwe = clean["llama"], clean["qwen"]
    w(f"  \\caption{{\\textbf{{Inserted material causes over-refusal, but only when it "
      f"carries meaning.}} Each category's spans were inserted into the same 300 benign "
      f"prompts, held out from the attack. Bars show the change in refusal rate against the "
      f"un-injected baseline of 0.7\\%, counting only refusals where an independent judge "
      f"confirmed the injected prompt still asks for something benign; whiskers are paired "
      f"bootstrap 95\\% intervals. Character noise and action words do not move refusal on "
      f"either model, while touchy subjects raise it "
      f"{lla['touchy']['delta']:+.1f}~pp on Llama, and all five together "
      f"{lla['all_five']['delta']:+.1f}~pp.}}")
    w("  \\label{fig:injection}")
    w("\\end{figure}")
    w("")

    # ---- Example boxes ---------------------------------------------------------
    w("% ---- worked examples, one box per category --------------------------------")
    for k in CLUSTERS:
        flips = [(i, r) for i, r in by.get(k, {}).items()
                 if r["label"] == "REFUSE" and base.get(i, {}).get("label") == "COMPLY"
                 and ben.get((k, i), "") != "SPOILED" and is_refusal(r["response"])]
        if not flips:
            w(f"% no example for {k}: no flip whose response is unambiguously a refusal")
            print(f"  [skip] {k}: no box (no unambiguous refusal among its flips)")
            continue
        flips.sort(key=lambda x: len(x[1]["prompt"]))
        i, r = flips[len(flips) // 4]
        w("\\begin{tcolorbox}[colback=boxgrey,colframe=black!25,boxrule=0.4pt,"
          "left=4pt,right=4pt,top=3pt,bottom=3pt,"
          f"title={{\\small\\bfseries {LABEL[k]}}},fonttitle=\\small]")
        w("\\small")
        w(f"\\textbf{{Original}}\\quad {esc(trim(base[i]['prompt'], 200))}\\\\[2pt]")
        w(f"\\textbf{{Rewrite}}\\quad {marked(base[i]['prompt'], r['prompt'], 240)}\\\\[2pt]")
        w(f"\\textbf{{Response}}\\quad \\emph{{{esc(trim(r['response'], 220))}}}")
        w("\\end{tcolorbox}")
        w("")

    # ---- Appendix table --------------------------------------------------------
    w("% ---- appendix: full per-arm injection results -----------------------------")
    w("\\begin{table}[t]")
    w("\\centering\\small")
    w("\\caption{\\textbf{Injection results, all arms and both targets.} Change in refusal "
      "rate on 300 held-out benign prompts against a 0.7\\% baseline, restricted to "
      "refusals where the injected prompt was confirmed still benign. Paired bootstrap 95\\% "
      "intervals; bold marks intervals excluding zero.}")
    w("\\label{tab:injection-full}")
    w("\\begin{tabular}{lcccc}")
    w("\\toprule")
    w("& \\multicolumn{2}{c}{Llama3-8B} & \\multicolumn{2}{c}{Qwen3-32B} \\\\")
    w("\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}")
    w("Injected material & $\\Delta$ (pp) & 95\\% CI & $\\Delta$ (pp) & 95\\% CI \\\\")
    w("\\midrule")
    for k in ARM_ORDER:
        c = []
        for t in ("llama", "qwen"):
            r = clean[t][k]
            d = f"{r['delta']:+.1f}"
            c.append(f"\\textbf{{{d}}}" if r["lo"] > 0 else d)
            c.append(f"[{r['lo']:+.1f}, {r['hi']:+.1f}]")
        sep = "\\midrule\n" if k == "chars+negation" else ""
        w(f"{sep}{ARM_LABEL[k]} & {c[0]} & {c[1]} & {c[2]} & {c[3]} \\\\")
    w("\\bottomrule")
    w("\\end{tabular}")
    w("\\end{table}")

    open(a.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {a.out}")
    print(f"  cluster table: {n:,} rewrites, {100*(n-none)/n:.1f}% covered by five categories")
    print(f"  example boxes: {sum(1 for k in CLUSTERS if by.get(k))} categories")


if __name__ == "__main__":
    main()
