#!/usr/bin/env python3
"""Fold the Qwen causal results into a side-by-side with Llama, so replication is legible.

Every causal claim in this project was Llama-only until now; the Qwen run mirrors it with the
same scripts, the same pre-registered criteria, and Qwen's own train-only direction basis.
This writes the comparison rather than leaving two JSONs to be diffed by hand.
"""
import json, math, os

def wil(p, n, z=1.96):
    if not n: return (0.0, 0.0)
    p /= 100; d = 1 + z*z/n
    c = (p + z*z/(2*n)) / d
    h = z*math.sqrt(p*(1-p)/n + z*z/(4*n*n)) / d
    return 100*(c-h), 100*(c+h)

def load(p):
    return json.load(open(p))["rates"] if os.path.exists(p) else None

L = ["# Llama vs Qwen — causal replication\n",
     "Same scripts, same pre-registered criteria (`k*` = smallest k with over-refusal below 50% "
     "of baseline AND harmful refusal above 80% of baseline AND coherent output), each model "
     "using its own train-only direction basis and its own refusal direction. Every number is "
     "measured on HELD-OUT originals.\n"]

pairs = [("Llama-3-8B", "probe_or/results/causal_rank.json", "probe_or/results/safety_power.json"),
         ("Qwen3-32B",  "probe_or/results/causal_rank_qwen.json", "probe_or/results/safety_power_qwen.json")]

L += ["\n## Causal rank sweep\n",
      "| model | k | over-refusal | random k | harmful refusal | originals | degenerate |",
      "|---|--:|--:|--:|--:|--:|--:|"]
kstars = {}
for name, cr, _ in pairs:
    R = load(cr)
    if not R:
        L.append(f"| {name} | — | _not yet available_ | | | | |"); continue
    K = int(R["_meta"]["K"]); b_or = R["or_rewrites__baseline"]; b_ad = R["advbench__baseline"]
    L.append(f"| **{name}** | 0 | {b_or:.1f}% | — | {b_ad:.1f}% | "
             f"{R['originals__baseline']:.1f}% | {R['originals__baseline__degen']:.1f}% |")
    ks = None
    for k in range(1, K+1):
        o = R[f"or_rewrites__ours_k{k}"]; rr = R[f"or_rewrites__random_k{k}"]
        ad = R[f"advbench__ours_k{k}"]; og = R[f"originals__ours_k{k}"]
        dg = R[f"originals__ours_k{k}__degen"]
        ok = (o < 0.5*b_or) and (ad > 0.8*b_ad) and dg <= 20
        if ok and ks is None: ks = k
        star = " ←k\\*" if (ok and ks == k) else ""
        L.append(f"| | {k}{star} | **{o:.1f}%** | {rr:.1f}% | {ad:.1f}% | {og:.1f}% | {dg:.1f}% |")
    kstars[name] = ks
    L.append(f"| | _atlas r̂_ | {R['or_rewrites__atlas_rhat']:.1f}% | — | "
             f"{R['advbench__atlas_rhat']:.1f}% | | |")

L += ["\n**k\\*** — " + " · ".join(f"{k}: **{v if v else 'not reached'}**" for k, v in kstars.items()) + "\n"]

L += ["\n## Powered safety test — does the effective direction spare safety on both models?\n",
      "| model | condition | over-refusal | harmful refusal | 95% CI | Δ vs baseline |",
      "|---|---|--:|--:|--:|--:|"]
for name, _, sp in pairs:
    R = load(sp)
    if not R:
        L.append(f"| {name} | — | _not yet available_ | | | |"); continue
    n = int(R["_meta"]["n_harmful"]); b = R["harmful__baseline"]
    conds = [c.split("harmful__")[1] for c in R
             if c.startswith("harmful__") and not c.endswith(("__degen", "__n"))]
    order = [c for c in ("baseline", "potent_d4", "shared_d1", "d1_plus_potent",
                         "atlas_rhat", "random_k1", "random_k2") if c in conds]
    for c in order:
        v = R[f"harmful__{c}"]; lo, hi = wil(v, n); o = R.get(f"or_rewrites__{c}", float("nan"))
        lbl = {"potent_d4": "**lexical-alarm direction**", "shared_d1": "shared axis",
               "d1_plus_potent": "both", "atlas_rhat": "literature r̂",
               "random_k1": "random k=1", "random_k2": "random k=2"}.get(c, c)
        L.append(f"| {name} | {lbl} | {o:.2f}% | {v:.2f}% | [{lo:.1f}, {hi:.1f}] | {v-b:+.2f}pp |")

L.append("\n---\nGenerated by `write_parity_report.py`. See `FINDINGS_STATUS.md` for the "
         "standing/retracted ledger and `HIGH_EDIT_FINDINGS.md` for the full Llama write-up.")
open("LLAMA_VS_QWEN.md", "w").write("\n".join(L) + "\n")
print("wrote LLAMA_VS_QWEN.md")
